use_frameworks!

target 'DYSafeObject_Example' do
  pod 'DYSafeObject', :path => '../'

  target 'DYSafeObject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
